services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - ./data/content:/app/content
      - ./data/auth:/app/data
      - ./data/logs:/app/data/logs
    restart: unless-stopped
    depends_on:
      - gotenberg
    environment:
      - NODE_ENV=production
      - GOTENBERG_URL=http://gotenberg:3000
    networks:
      - catequesis-network

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3002:3000"
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-web-security"
      - "--chromium-allow-list=file:///*"
    networks:
      - catequesis-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  catequesis-network:
    driver: bridge

volumes:
  content-data:
    driver: local