version: '3.8'

services:
  catequesis-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
      - READ_ONLY=${READ_ONLY:-false}
      - VISIBILITY_MODE=${VISIBILITY_MODE:-publish}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    volumes:
      # Volumen persistente para el contenido
      - ./content:/app/content:rw
      # Volumen para logs de auditoría
      - audit_logs:/app/content/.audit.log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  audit_logs:
    driver: local

networks:
  default:
    name: catequesis-network