services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - ./data/content:/app/content:ro
      - ./data/auth:/app/data:rw
      - ./data/logs:/app/data/logs:rw
    restart: always
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/.next/cache:noexec,nosuid,size=200m
    environment:
      - NODE_ENV=production
    networks:
      - catequesis-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  catequesis-network:
    driver: bridge

volumes: {}
