version: "3.9"

services:
  gotenberg:
    image: gotenberg/gotenberg:8
    command: 
      - "gotenberg"
      - "--api-port=3000"
      - "--api-timeout=15s"
      - "--libreoffice-disable-routes=false"
      - "--chromium-disable-web-security"
      - "--chromium-allow-list=file:///*"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: "3001"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: "production"
      GOTENBERG_URL: "http://gotenberg:3000"
    depends_on:
      gotenberg:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./data/content:/app/content:ro
      - ./data/logs:/app/data/logs
    networks:
      - public
      - internal
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/.next/cache:noexec,nosuid,size=200m
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "768M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/api/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  content-data:
    driver: local